### ISSUE TITLE
Unable to write crypto into vault

### ISSUE THREAD

**Issue by shanmukh-777** [hyperledger/bevel#2381]
Recently when i trying to deploy indy using bevel helmcharts, I am unable to write crypto generated by hyperledgerlabs/indy-key-mgmt image into vault getting ssl certificate failed using kubernetes job but i never provided a certificate to it. Can some one help me with this issue
This is the error i am getting
2023-10-03 06:07:33,087|DEBUG|connectionpool.py|Starting new HTTPS connection (1): vault.vault:8200
Traceback (most recent call last):
  File "/.virtualenvs/baf/lib/python3.5/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/.virtualenvs/baf/lib/python3.5/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/.virtualenvs/baf/lib/python3.5/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/.virtualenvs/baf/lib/python3.5/site-packages/urllib3/connection.py", line 421, in connect
    tls_in_tls=tls_in_tls,
  File "/.virtualenvs/baf/lib/python3.5/site-packages/urllib3/util/ssl_.py", line 450, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "/.virtualenvs/baf/lib/python3.5/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.virtualenvs/baf/lib/python3.5/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/.virtualenvs/baf/lib/python3.5/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/.virtualenvs/baf/lib/python3.5/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='vault.vault', port=8200): Max retries exceeded with url: /v1/sys/mounts/secret/tune (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.virtualenvs/baf/bin/generate_identity", line 6, in <module>
    IdentityCreator.process()
  File "/.virtualenvs/baf/lib/python3.5/site-packages/plenum/common/identity_crypto_generator.py", line 305, in process
    vault.upload(data=identity)
  File "/.virtualenvs/baf/lib/python3.5/site-packages/plenum/common/identity_crypto_generator.py", line 231, in upload
    provider_exists, _ = self.read_data(url=provider_url, headers=headers)
  File "/.virtualenvs/baf/lib/python3.5/site-packages/plenum/common/identity_crypto_generator.py", line 263, in read_data
    response = requests.get(url=url, headers=headers)
  File "/.virtualenvs/baf/lib/python3.5/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/.virtualenvs/baf/lib/python3.5/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/.virtualenvs/baf/lib/python3.5/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/.virtualenvs/baf/lib/python3.5/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/.virtualenvs/baf/lib/python3.5/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='vault.vault', port=8200): Max retries exceeded with url: /v1/sys/mounts/secret/tune (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),))

**Comment by suvajit-sarkar** [comment]
How are you deploying vault and what value are you using in vault.url of network yaml file?
